# Usamos una imagen de Node que ya incluye pnpm
FROM node:18-slim

# Activamos pnpm
RUN corepack enable

# Establecemos el directorio de trabajo
WORKDIR /app

# Copiamos los archivos de manifiesto para instalar dependencias
# Docker usará el caché si no han cambiado, haciendo todo más rápido
COPY package.json pnpm-lock.yaml ./

# Instalamos las dependencias
RUN pnpm install

# Exponemos el puerto del servidor de desarrollo de Vite
EXPOSE 5173

# El comando para iniciar el servidor de desarrollo.
# El flag '--host' es CRUCIAL para que sea accesible desde fuera del contenedor.
CMD ["pnpm", "run", "dev", "--host"]