# docker-compose.yml
version: '3.8'

services:

  # --- Servicio de Ollama (IA Embeddings) ---
  ollama:
    container_name: phoenix_ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - fenix-net # <-- Usa fenix-net

  # --- Servicio del Backend (Go + Gin) ---
  backend:
    container_name: phoenix_backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      GIN_MODE: debug
      MEILI_HOST: http://meilisearch:7700
      MEILI_MASTER_KEY: unaclavesupersecreta123
      OLLAMA_URL: http://ollama:11434 # <-- AÑADIDO
    depends_on:
      - meilisearch
      - ollama # <-- AÑADIDO
    restart: unless-stopped
    networks:
      - fenix-net # <-- Usa fenix-net

  # --- Servicio del Frontend (SvelteKit) ---
  frontend:
    container_name: phoenix_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - fenix-net # <-- Usa fenix-net

  # --- Servicio de Búsqueda (MeiliSearch) ---
  meilisearch:
    container_name: phoenix_meilisearch
    image: getmeili/meilisearch:v1.3 # Considera usar una versión más reciente si hay
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=unaclavesupersecreta123
      - MEILI_ENV=development
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped
    networks:
      - fenix-net # <-- Usa fenix-net

# Definición de las redes personalizadas
networks:
  fenix-net: # <-- Usa fenix-net
    driver: bridge

# Definición de los volúmenes nombrados
volumes:
  ollama_data:
  meili_data:
    driver: local